version: '3.3'

services:
  kp-votes:
    container_name: kp-votes
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      KpVotes_TwitterCredentials__AccessSecret: 123
      KpVotes_TwitterCredentials__AccessToken: 123
      KpVotes_TwitterCredentials__ConsumerKey: 123
      KpVotes_TwitterCredentials__ConsumerSecret: 123
    volumes:
      - ./data:/var/opt/kp-votes

volumes:
  data:
