services:
  lightpanda:
    image: lightpanda/browser:nightly
    container_name: lightpanda
    restart: unless-stopped

  app:
    build: .
    container_name: kpvotes
    restart: unless-stopped
    depends_on:
      - lightpanda
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - YOBACONF_ENDPOINT=${YOBACONF_ENDPOINT}
      - YOBACONF_API_KEY=${YOBACONF_API_KEY}
